oro.security:
  config_dir: vendor:oroshi/oro-security/config
  migration_dir: vendor:oroshi/oro-security/migration
  fixture_dir: vendor:oroshi/oro-security/fixture
  mount: ''
  login:
    token_expiry: +1 month
  jwt:
    issuer: ${project.name}
    audience: ${project.name}
    secret: 'changeme'


oro.testing:
  config_dir: crates:oro-testing/config
  migration_dir: crates:oro-testing/migration
  fixture_dir: crates:oro-testing/fixture
  mount: '/testing'
