#
# Project settings for the web context
#

cors:
  enabled: true
  scheme: http
  host: localhost
  request:
    allowed_origins: ['*']
    allowed_headers: ['accept', 'origin', 'content-type', 'x-xsrf-token']
    allowed_methods: ['GET', 'POST', 'PUT', 'DELETE']
    allowed_credentials: true
  response:
    preflight_cache_max_age: 600
    exposed_headers:
      - Access-Control-Allow-Origin
      - Access-Control-Allow-Credentials
      - Access-Control-Max-Age
