storage_adapters:
  oro.security.user.standard:
    class: Daikon\Elasticsearch6\Storage\Elasticsearch6StorageAdapter
    connector: oro.security.projection_store
    settings:
      index: ${project.prefix}.oro-security.user.standard
      type: oro-security-user-standard

projectors:
  oro.security.user.standard:
    class: Daikon\ReadModel\Projector\StandardProjector
    repository: oro.security.user.standard
    events:
    - Oro\Security\User\Register\UserWasRegistered
    - Oro\Security\User\Activate\UserWasActivated

repositories:
   oro.security.user.standard:
     class: Oro\Security\ReadModel\Standard\UserRepository
     storage_adapter: oro.security.user.standard
